spring.application.name=employee-api

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Development only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true